### ISSUE TITLE
Odata request url is not formed properly

### ISSUE THREAD

**Issue by hussainih** [d365collaborative/d365fo.integrations#5]
When executing Export-D365OData as demostrated in the code below, it will not form a proper url to request Entity. d365 fo return error stating that the entity is not found. It looks like the path '/data' is missing in url. The work around for now is to include the path as prefix in '-Entity' parameter for example 'data/Customers'
`Export-D365OData -Authority https://login.windows.net/myd365fotenant.onmicrosoft.com -ClientId clientId -ClientSecret secrete -D365FOUrl https://usnconeboxax1aos.cloud.onebox.dynamics.com -Entity Customers`.
Appending the path '/data' to D365FOUrl parameter generate error as below
`Exception calling "Wait" with "1" argument(s): "One or more errors occurred."
At line:10 char:5
+     $taskStatus = $task.Wait(1000)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : AggregateException`

**Comment by ITRasmus** [comment]
Hi
The function is created so you should do -Entity 'data/Customers'.
Could you try this and see if this works ?

**Comment by hussainih** [comment]
Hi, 
Yes it does work if I pass parameter as you described.

**Comment by Splaxi** [comment]
And we are working on refactoring the entire module, so things will change a fair bit in the next release.

But we will ensure to document things as good as we can.
