### ISSUE TITLE
Running OData cmdlets which exceed 1 hour

### ISSUE THREAD

**Issue by smholvoet** [d365collaborative/d365fo.integrations#54]
Hi 👋

I'm running the following command which exports records from a data entity which has quite a few records.

```powershell
$StartDate = '2021-01-01T12:00:00Z'
$EndDate =   '2021-12-31T12:00:00Z'
$Company =   'xyz'
$Filters = @("TransDate ge $StartDate",
             "TransDate le $EndDate",
             "dataAreaId eq '$Company'")

$LedgerJournalLines = Get-D365ODataEntityData -EntityName "LedgerJournalCDSLines" -Filter $Filters -TraverseNextLink -CrossCompany -Verbose

Write-Host "Exporting $($LedgerJournalLines.Length) rows..."

$LedgerJournalLines | Export-Csv "xyz\$($Company)-LedgerJournalCDSLines.csv" -NoTypeInformation

```

The entity in question should export > 1 million worth of records, thankfully `-TraverseNextLink` nicely gets 10k records at a time, this works great 💪.

However, the access token which gets requested during the initial request times out after 1 hour by default. This results in a `401: Unauthorized` as the cmdlet keeps sending out requests with the 1 hour old access token and eventually fails if the runtime exceeds 60 minutes:

```text
 Something went wrong while retrieving data from the OData endpoint for the entity: LedgerJournalCDSLines | Response status code does not indicate success: 401 (Unauthorized).
```

This would obviously apply to any of the OData related  (Update, Remove, ....) cmdlets which exceed this duration.

Is there a workaround I could apply?

**Comment by Splaxi** [comment]
That is the first time we hit it. 

Normally we recommend to handle the token refresh in a outer loop - but then you also have to handle the traverse part yourself 🤷‍♂️

It would require quite some rework to handle it on the inside of the functions

**Comment by smholvoet** [comment]
Alright, thanks for the info.

I've split up my original function in multiple chunks (using the date filters) so the runtime stays below 1h. I'll go ahead and close this one.
