### ISSUE TITLE
Branch : Refactor - Download URL is Https on MS hosted

### ISSUE THREAD

**Issue by ITRasmus** [d365collaborative/d365fo.integrations#6]
@Splaxi  On a MS hosted Environment the URL for downloading and ack is HTTPS.

https://github.com/d365collaborative/d365fo.integrations/blob/9634668cce83cb23ad8f7bbc931a67ee5815e355/d365fo.integrations/internal/functions/get-dmffile.ps1#L54

**Comment by Splaxi** [comment]
I believe I fixed it in a newer version
