### ISSUE TITLE
:question: Remove "required" module Azure.Storage?

### ISSUE THREAD

**Issue by FH-Inway** [d365collaborative/d365fo.integrations#65]
This module has Azure.Storage listed as required module, which is part of the AzureRM PowerShell modules that will be retired next year (https://learn.microsoft.com/en-us/powershell/azure/migrate-from-azurerm-to-az).

https://github.com/d365collaborative/d365fo.integrations/blob/7f14ea3d3b3c787e7b881e44265e39ddce0112cf/d365fo.integrations/d365fo.integrations.psd1#L26-L33

I did a check with [New-AzUpgradeModulePlan](https://learn.microsoft.com/en-us/powershell/azure/quickstart-migrate-azurerm-to-az-automatically) to see which cmdlets would need to be changed to upgrade this dependency to Az.Storage. However, this does not list any cmdlets. After some searches in the repo and inspecting some cmdlets manually, I think that the Azure.Storage module is not actually used by d365fo.integrations. 

If that is correct, I propose that Azure.Storage is removed as required module. Otherwise, it should be changed to Az.Storage.

The idea behind this is that we could use d365fo.integrations (which has a smaller user base than d365fo.tools) for a sort of trial run to upgrade the Azure.Storage dependency. 

See also https://github.com/d365collaborative/d365fo.tools/issues/361

**Comment by Splaxi** [comment]
I'm all in!

**Comment by FH-Inway** [comment]
@Splaxi Could you release a new version so this issue can be closed?

**Comment by FH-Inway** [comment]
Version 0.4.39 does no longer have the dependencies.

@Splaxi Thanks for the release.
