### ISSUE TITLE
PackageManagement\Install-Package : Unable to find dependent module(s) (AzureRM.Profile)

### ISSUE THREAD

**Issue by draganya** [d365collaborative/d365fo.integrations#71]
Hi, installing with PS command:
 Install-Module -Name d365fo.integrations
gives  you the following error:
WARNING: Could not get response from query
'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='AzureRM.Profile'&$skip=0&$top=40'.
PackageManagement\Install-Package : Unable to find dependent module(s) (AzureRM.Profile)
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (AzureRM.Profile:String) [Install-Package], Exception
    + FullyQualifiedErrorId : UnableToFindDependencyPackage,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPack
   age

**Comment by Splaxi** [comment]
On it - have been hitting this issue for the last few hours.

**Comment by Splaxi** [comment]
0.4.39 solves the issue

**Comment by draganya** [comment]
Thank you!
